# fly.toml app configuration file generated for untrusted-python on 2023-07-25T20:38:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "untrusted-python"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
